### PR TITLE
Install and start plugin by CLI

### PR DESCRIPTION
**Pull request by rootwarp**
### 1. Type of change

Please delete options that are not relevant.

- [X] New feature
- [ ] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)
relate #298 

**Summary**

Provide install and start command of plugin.

---

This is not the PR for merging. Just only for reviewing current usability and discuss this feature is feasible or not.

~~Due to the `vatz-plugin-cosmoshub` repository is private repo, testers are required to issue Github token for accessing the repo programmatically.~~

The plugin can be installed by,
```
rootwarp@mindhack ~/g/vatz install > ./vatz plugin install github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status cosmos-status
2022-11-21T02:54:53Z INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status module=plugin
2022-11-21T02:54:53Z INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status module=plugin
Username for 'https://github.com': rootwarp
Password for 'https://rootwarp@github.com':
2022-11-21T02:54:58Z INF newWriter module=db
2022-11-21T02:54:58Z INF Create DB Instance module=db
```

Then, it can be started by, 
```
rootwarp@mindhack ~/g/vatz install > ./vatz plugin start --plugin cosmos-status --args "--valoperAddr=cosmosvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02rmvmsu"
2022-11-21T02:57:14Z INF Start plugin cosmos-status%!(EXTRA string=--valoperAddr=cosmosvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02rmvmsu) module=plugin
2022-11-21T02:57:14Z INF Start plugin cosmos-status module=plugin
2022-11-21T02:57:14Z INF newReader module=db
2022-11-21T02:57:14Z INF Create DB Instance module=db
```

The process of the plugin will be running background.

```
rootwarp@mindhack ~/g/vatz install > ps -ef|grep cosmos-status
rootwarp 1044661       1  0 02:57 pts/4    00:00:00 /home/rootwarp/.vatz/cosmos-status --valoperAddr=cosmosvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02rmvmsu
rootwarp 1044695 1043951  0 02:57 pts/4    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox cosmos-status
rootwarp@mindhack ~/g/vatz install >
```

To be enhanced on the next step.
- Get feedback and have discussion -> N/A
- Provide precise error messages -> Added
- Separate test from the real environment. Currently test try to install the plugin from real plugin repository, which is not feasible in unittest env -> TBD
- Separate SQLite DB driver for enhancing reusability -> TBD

### CODE REVIEW

**Comment by rootwarp** [comment]
@dsrvlabs/validator Please review this PR.
Regarding to refactoring, I think it could be better on the other issues after the plugin CLI features are working well.

**Comment by xellos00** [comment]
> @dsrvlabs/validator Please review this PR. Regarding to refactoring, I think it could be better on the other issues after the plugin CLI features are working well.

agree, this has to be reviewed first.

**Comment by xellos00** [comment]
@rootwarp 

### 1. Create a home directory if there's no `.vatz` directory under home path 
Do I need to create my own `.vatz` folder at home directory?
I don't see any code that does create folder if there's no name for .vatz folder.
Can we put the code create a folder if there's no .vatz directory?

### 2. Can we put code automatically, get rid of https:// or http?
I think when people try to install plugin with vatz, then I guess they will copy and paste url. 
```
 ./vatz plugin install https://github.com/dsrvlabs/vatz-plugin-sysutil sysutil                      
2022-11-28T21:34:30-06:00 INF Install new plugin https://github.com/dsrvlabs/vatz-plugin-sysutil at /Users/dongyookang/.vatz module=plugin
2022-11-28T21:34:30-06:00 INF Install new plugin https://github.com/dsrvlabs/vatz-plugin-sysutil module=plugin
Error: exit status 1
Usage:
   plugin install [flags]

Examples:
vats plugin install github.com/dsrvlabs/<somewhere> name

Flags:
  -h, --help   help for install

panic: exit status 1

goroutine 1 [running]:
main.main()
        /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/main.go:20 +0x45

```

3. Errors occurs? any idea? 
```
 ✘ dongyookang DK 🦄   ~/ffplay/GolandProjects/dsrvlabs/vatz   install ±
 ./vatz plugin install github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status cosmos-status
2022-11-28T21:36:01-06:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status at /Users/dongyookang/.vatz module=plugin
2022-11-28T21:36:01-06:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status module=plugin
Error: exit status 1
Usage:
   plugin install [flags]

Examples:
vats plugin install github.com/dsrvlabs/<somewhere> name

Flags:
  -h, --help   help for install

panic: exit status 1

goroutine 1 [running]:
main.main()
        /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/main.go:20 +0x45
 ✘ dongyookang DK 🦄   ~/ffplay/GolandProjects/dsrvlabs/vatz   install ±

```

**Comment by rootwarp** [comment]
@xellos00 Thanks for feedback 👍 

I leave some responses.

1. Create a home directory if there's no .vatz directory under home path
For now, `.vatz` directory will no be created automatically and I think it should be fixed in this issue.

2. Can we put code automatically, get rid of https:// or http?
Good point. `install` code inherits the exact `go install` command so `https://` prefix should be removed. I'll add new code to handle those prefixes.

4. Errors occurs? any idea?
Would be mind testing again with another repo address?
it seems `github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status` is renamed to `github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status`.

**Comment by xellos00** [comment]
> 3\. github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status

Yeah, it's working 

```
 ./vatz plugin install github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status cosmos-status
2022-11-28T22:21:50-06:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status at /Users/dongyookang/.vatz module=plugin
2022-11-28T22:21:50-06:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status module=plugin
2022-11-28T22:21:54-06:00 INF newWriter module=db
2022-11-28T22:21:54-06:00 INF Create DB Instance module=db

```

I think it's good to have message that such as 

`Cannot find given plugin address "github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status".
Please, Check repo's availability`

what do you think?

**Review by meetrick — APPROVED** [review]
LGTM

**Comment by rootwarp** [comment]
> 

@xellos00 If you test with latest commit, you can see new log message in that situation.

```
rootwarp@mindhack ~/g/vatz install! > ./vatz plugin install github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status cosmos-status
2022-11-29T07:50:06Z INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status at /home/rootwarp/.vatz module=plugin
2022-11-29T07:50:06Z INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status module=plugin
2022-11-29T07:50:06Z ERR go: github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status@latest: module github.com/dsrvlabs/vatz-plugin-cosmoshub@latest found (v0.0.0-20221125041253-21798cb5d793), but does not contain package github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/active_status
```

At the above, the last line describes error and the message is retrieved from result of the command execution.

**Comment by rootwarp** [comment]
@xellos00 And please check [this](https://github.com/dsrvlabs/vatz/pull/307#issuecomment-1330045888) again. item 1 could be resolved.

**Comment by rootwarp** [comment]
@xellos00 I pushed a new commit to my forked repo at `07ace55b9c9fb66cd68a06a646ad7f7fcf2500b3` but this PR is not updated.
I think some problems are happening after changing this project as public.
Do you have any idea?

**Comment by xellos00** [comment]
> And please check [this](https://github.com/dsrvlabs/vatz/pull/307#issuecomment-1330045888) again. item 1 could be resolved.

Let's close this PR, send another PR. 
does it work for you?

**Comment by rootwarp** [comment]
Move to #317

**Pull request closed without merging**
