### PR TITLE
Add global flag --config for plugin

### LINKED ISSUE #481: plugin command can't load specified config
### Checklist
- [x] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

If we want to specify config file(not using default.yaml), we can add `--config` flag to start `vatz`.
But when we try to install plugins by using `plugin` command, `--config` flag is not available to specify Vatz config right now.

`start` command supports `--config` flag.
```
rootwarp@mindhack ~/g/d/vatz test? > ./vatz start --help
start VATZ

Usage:
   start [flags]

Flags:
      --config string       VATZ config file. (default "default.yaml")
  -h, --help                help for start
      --log string          log file export to.
      --prometheus string   prometheus port number. (default "18080")
```

But `plugin` command does not.
```
rootwarp@mindhack ~/g/d/vatz test? > ./vatz plugin install --help
Install new plugin

Usage:
   plugin install [flags]

Examples:
vatz plugin install <plugin's githubAddress> <pluginName>

Flags:
  -h, --help             help for install
  -v, --version string   Installed plugin version
```

`--config` flag should be available for all `plugin` command.
Additionally, the specified config file should be loaded appropriately.

N/A

### PR DESCRIPTION
**Pull request by rootwarp**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Enhancement
- [x] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)
close #481 

**Summary**

Enable `--config` flag for `plugin` subcommands.

---

### CODE REVIEW

**Comment by rootwarp** [comment]
# Build.
```
ok      github.com/dsrvlabs/vatz/utils  (cached)
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    1.568s  coverage: 23.8% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.011s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.009s  coverage: 77.8% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.013s  coverage: 7.1% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       0.015s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.011s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 1.218s  coverage: 50.6% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  0.014s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    1.012s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.007s  coverage: 7.1% of statements
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=issue#481' -X 'github.com/dsrvlabs/vatz/utils.Commit=a1638d9'" -v
github.com/dsrvlabs/vatz
```

**Comment by rootwarp** [comment]
# Test flags.

For the default environment.
```
rootwarp@mindhack ~/g/d/vatz issue#481? > ./vatz init
2023-07-10T10:42:42Z INF init module=main
2023-07-10T10:42:42Z INF home path ~/.vatz module=main
2023-07-10T10:42:42Z INF create file default.yaml module=main
2023-07-10T10:42:42Z INF Load Config default.yaml module=config
2023-07-10T10:42:42Z INF Plugin dir /home/rootwarp/.vatz module=main
2023-07-10T10:42:42Z INF Create DB Instance module=db
2023-07-10T10:42:42Z INF initDB /home/rootwarp/.vatz/vatz.db module=db
2023-07-10T10:42:42Z INF Remove old DB file module=db
2023-07-10T10:42:42Z INF Create new DB file module=db
2023-07-10T10:42:42Z INF Create DB Instance module=db
rootwarp@mindhack ~/g/d/vatz issue#481? > ./vatz plugin list
2023-07-10T10:42:48Z INF Load Config default.yaml module=config
2023-07-10T10:42:48Z INF List plugins module=plugin
2023-07-10T10:42:48Z INF Create DB Instance module=db
2023-07-10T10:42:48Z INF List module=plugin
2023-07-10T10:42:48Z INF List module=db
+------+------------+--------------+------------+---------+
| NAME | IS ENABLED | INSTALL DATE | REPOSITORY | VERSION |
+------+------------+--------------+------------+---------+
+------+------------+--------------+------------+---------+
rootwarp@mindhack ~/g/d/vatz issue#481? > ./vatz plugin install https://github.com/dsrvlabs/vatz-plugin-sysutil/plugins/disk_monitor disk_monitor
2023-07-10T10:43:26Z INF Load Config default.yaml module=config
2023-07-10T10:43:26Z INF Install new plugin https://github.com/dsrvlabs/vatz-plugin-sysutil/plugins/disk_monitor at /home/rootwarp/.vatz. module=plugin
2023-07-10T10:43:26Z INF Installing plugin version is latest. module=plugin
2023-07-10T10:43:26Z INF Create DB Instance module=db
2023-07-10T10:43:26Z INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/disk_monitor module=plugin
2023-07-10T10:43:29Z INF AddPlugin module=db
rootwarp@mindhack ~/g/d/vatz issue#481? > ./vatz plugin list
2023-07-10T10:43:33Z INF Load Config default.yaml module=config
2023-07-10T10:43:33Z INF List plugins module=plugin
2023-07-10T10:43:33Z INF Create DB Instance module=db
2023-07-10T10:43:33Z INF List module=plugin
2023-07-10T10:43:33Z INF List module=db
+--------------+------------+---------------------+----------------------------------------------------------------------+---------+
| NAME         | IS ENABLED | INSTALL DATE        | REPOSITORY                                                           | VERSION |
+--------------+------------+---------------------+----------------------------------------------------------------------+---------+
| disk_monitor | true       | 2023-07-10 10:43:29 | https://github.com/dsrvlabs/vatz-plugin-sysutil/plugins/disk_monitor | latest  |
+--------------+------------+---------------------+----------------------------------------------------------------------+---------+
rootwarp@mindhack ~/g/d/vatz issue#481? >
```

for the second environment.
```
rootwarp@mindhack ~/g/d/vatz issue#481? > ./vatz init --home ~/vatz2 --output second.yaml
2023-07-10T10:46:17Z INF init module=main
2023-07-10T10:46:17Z INF home path /home/rootwarp/vatz2 module=main
2023-07-10T10:46:17Z INF create file second.yaml module=main
2023-07-10T10:46:17Z INF Load Config second.yaml module=config
2023-07-10T10:46:17Z INF Plugin dir /home/rootwarp/vatz2 module=main
2023-07-10T10:46:17Z INF Create DB Instance module=db
2023-07-10T10:46:17Z INF initDB /home/rootwarp/vatz2/vatz.db module=db
2023-07-10T10:46:17Z INF Remove old DB file module=db
2023-07-10T10:46:17Z INF Create new DB file module=db
2023-07-10T10:46:17Z INF Create DB Instance module=db
rootwarp@mindhack ~/g/d/vatz issue#481? > ./vatz plugin install https://github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor cpu_monitor --config ./second.yaml
2023-07-10T10:46:33Z INF Load Config ./second.yaml module=config
2023-07-10T10:46:33Z INF Install new plugin https://github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor at /home/rootwarp/vatz2. module=plugin
2023-07-10T10:46:33Z INF Installing plugin version is latest. module=plugin
2023-07-10T10:46:33Z INF Create DB Instance module=db
2023-07-10T10:46:33Z INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor module=plugin
2023-07-10T10:46:33Z INF AddPlugin module=db
rootwarp@mindhack ~/g/d/vatz issue#481? > ./vatz plugin list --config ./second.yaml
2023-07-10T10:46:42Z INF Load Config ./second.yaml module=config
2023-07-10T10:46:42Z INF List plugins module=plugin
2023-07-10T10:46:42Z INF Create DB Instance module=db
2023-07-10T10:46:42Z INF List module=plugin
2023-07-10T10:46:42Z INF List module=db
+-------------+------------+---------------------+---------------------------------------------------------------------+---------+
| NAME        | IS ENABLED | INSTALL DATE        | REPOSITORY                                                          | VERSION |
+-------------+------------+---------------------+---------------------------------------------------------------------+---------+
| cpu_monitor | true       | 2023-07-10 10:46:33 | https://github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor | latest  |
+-------------+------------+---------------------+---------------------------------------------------------------------+---------+
rootwarp@mindhack ~/g/d/vatz issue#481? >
```

**Comment by rootwarp** [comment]
@skonhwang Can you please test this?

**Review by skonhwang — APPROVED** [review]

**Comment by xellos00** [comment]
```
 dongyookang DK 🎉   ~/ffplay/GolandProjects/dsrvlabs/vatz   issue#481 ±✚
  ./vatz plugin install github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor cpu_monitor --config second.yaml
2023-07-13T21:35:59-05:00 INF Load Config second.yaml module=config
2023-07-13T21:35:59-05:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor at /Users/dongyookang/.vatz_test. module=plugin
2023-07-13T21:35:59-05:00 INF Installing plugin version is latest. module=plugin
2023-07-13T21:35:59-05:00 INF Create DB Instance module=db
2023-07-13T21:35:59-05:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor module=plugin
2023-07-13T21:36:06-05:00 INF AddPlugin module=db
 dongyookang DK 🎉   ~/ffplay/GolandProjects/dsrvlabs/vatz   issue#481 ±✚
 ./vatz plugin list --c second.yaml                  
Error: unknown flag: --c
Usage:
   plugin list [flags]

Examples:
vatz plugin list

Flags:
  -h, --help   help for list

Global Flags:
      --config string   VATZ config file. (default "default.yaml")

2023-07-13T21:36:30-05:00 ERR VATZ CLI command Error: unknown flag: --c
 dongyookang DK 🎉   ~/ffplay/GolandProjects/dsrvlabs/vatz   issue#481 ±✚
 ./vatz plugin list -c second.yaml 
Error: unknown shorthand flag: 'c' in -c
Usage:
   plugin list [flags]

Examples:
vatz plugin list

Flags:
  -h, --help   help for list

Global Flags:
      --config string   VATZ config file. (default "default.yaml")

2023-07-13T21:37:23-05:00 ERR VATZ CLI command Error: unknown shorthand flag: 'c' in -c
 dongyookang DK 🎉   ~/ffplay/GolandProjects/dsrvlabs/vatz   issue#481 ±✚
 ./vatz plugin list --config second.yaml
2023-07-13T21:37:31-05:00 INF Load Config second.yaml module=config
2023-07-13T21:37:31-05:00 INF List plugins module=plugin
2023-07-13T21:37:31-05:00 INF Create DB Instance module=db
2023-07-13T21:37:31-05:00 INF List module=plugin
2023-07-13T21:37:31-05:00 INF List module=db
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
| NAME        | IS ENABLED | INSTALL DATE        | REPOSITORY                                                  | VERSION |
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
| cpu_monitor | true       | 2023-07-13 21:36:06 | github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor | latest  |
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
 dongyookang DK 🎉   ~/ffplay/GolandProjects/dsrvlabs/vatz   issue#481 ±✚
 

```

**Comment by rootwarp** [comment]
@xellos00 Regarding "short form" of the command, I just use same term of `start` command and `start` command don't have short form too.

I think, it would be better add short form of the command form the new issue.

**Comment by xellos00** [comment]
> 

No, don't worry. I also agree that some of flag should not be in short form.

**Review by xellos00 — APPROVED** [review]

**Pull request merged**
