### PR TITLE
Fix the github action of creation bi weekly discussion

### PR DESCRIPTION
**Pull request by gnongs**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Enhancement
- [x] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

- **Related:** #560 

**Summary**
Fix the bug about not creation the discussion.

---

### 3. Comments

Before the this github action merge, we need to set the value like below.

- Secrets
  - REPOSITORY_ID
  - CATEGORY_ID

  
- Variables
  - START_DATE=2024-06-05
  
> How to get the REPOSITORY_ID and CATEGORY_ID
> You can run the below code with editing the <YOUR_GITHUB_TOKEN>
> 
> ```sh
> #!/bin/bash
> 
> # GitHub Personal Access Token
> TOKEN=<YOUR_GITHUB_TOKEN>
> 
> # GitHub GraphQL API Endpoint
> URL="https://api.github.com/graphql"
> 
> # GraphQL Query
> QUERY='{
> "query": "query { repository(owner: \"dsrvlabs\", name: \"vatz\") { id discussionCategories(first: 10) { edges { node { id name } cursor } } } }"
> }'
> 
> # Sending the request using curl
> response=$(curl -s -X POST -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -d "$QUERY" $URL)
> 
> # Output the response
> REPOSITORY_ID=`echo $response | jq .data.repository.id`
> CATEGORY_ID=`echo $response | jq .data.repository.discussionCategories.edges[1].node.id`
> 
> echo "REPOSITORY_ID: $REPOSITORY_ID"
> echo "CATEGORY_ID: $CATEGORY_ID"
> ```

> What is mean the START_DATE?
> A. START_DATE is the date on which Biweekly discussion is created. For example, if the standard date changes, as we did with June 5th as the new standard date, you can edit the value.
> Please enter the form as YYYY-MM-DD.

### CODE REVIEW

**Comment by xellos00** [comment]
@gnongs 
Guess we need to test overall right? in real cuz it's github action
let's put into test.

**Review by xellos00 — APPROVED** [review]

**Comment by gnongs** [comment]
@xellos00 I tested this action on my personal repo. We'll leave the reviews to other members.

**Comment by gnongs** [comment]
@xellos00 Before the merge, please check the below :)

- Secrets
  - REPOSITORY_ID
  - CATEGORY_ID

  
- Variables
  - START_DATE=2024-06-05
  
> How to get the REPOSITORY_ID and CATEGORY_ID
> You can run the below code with editing the <YOUR_GITHUB_TOKEN>
> 
> ```sh
> #!/bin/bash
> 
> # GitHub Personal Access Token
> TOKEN=<YOUR_GITHUB_TOKEN>
> 
> # GitHub GraphQL API Endpoint
> URL="https://api.github.com/graphql"
> 
> # GraphQL Query
> QUERY='{
> "query": "query { repository(owner: \"dsrvlabs\", name: \"vatz\") { id discussionCategories(first: 10) { edges { node { id name } cursor } } } }"
> }'
> 
> # Sending the request using curl
> response=$(curl -s -X POST -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -d "$QUERY" $URL)
> 
> # Output the response
> REPOSITORY_ID=`echo $response | jq .data.repository.id`
> CATEGORY_ID=`echo $response | jq .data.repository.discussionCategories.edges[1].node.id`
> 
> echo "REPOSITORY_ID: $REPOSITORY_ID"
> echo "CATEGORY_ID: $CATEGORY_ID"
> ```

> What is mean the START_DATE?
> A. START_DATE is the date on which Biweekly discussion is created. For example, if the standard date changes, as we did with June 5th as the new standard date, you can edit the value.
> Please enter the form as YYYY-MM-DD.

**Comment by xellos00** [comment]
> @xellos00 Before the merge, please check the below :)
> 
> * Secrets
>   
>   * REPOSITORY_ID
>   * CATEGORY_ID
> * Variables
>   
>   * START_DATE=2024-06-05
> 
> > How to get the REPOSITORY_ID and CATEGORY_ID
> > You can run the below code with editing the <YOUR_GITHUB_TOKEN>
> > ```shell
> > #!/bin/bash
> > 
> > # GitHub Personal Access Token
> > TOKEN=<YOUR_GITHUB_TOKEN>
> > 
> > # GitHub GraphQL API Endpoint
> > URL="https://api.github.com/graphql"
> > 
> > # GraphQL Query
> > QUERY='{
> > "query": "query { repository(owner: \"dsrvlabs\", name: \"vatz\") { id discussionCategories(first: 10) { edges { node { id name } cursor } } } }"
> > }'
> > 
> > # Sending the request using curl
> > response=$(curl -s -X POST -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -d "$QUERY" $URL)
> > 
> > # Output the response
> > REPOSITORY_ID=`echo $response | jq .data.repository.id`
> > CATEGORY_ID=`echo $response | jq .data.repository.discussionCategories.edges[1].node.id`
> > 
> > echo "REPOSITORY_ID: $REPOSITORY_ID"
> > echo "CATEGORY_ID: $CATEGORY_ID"
> > ```
> 
> > What is mean the START_DATE?
> > A. START_DATE is the date on which Biweekly discussion is created. For example, if the standard date changes, as we did with June 5th as the new standard date, you can edit the value.
> > Please enter the form as YYYY-MM-DD.

@gnongs 
Can you get someone to review to merge? 

and registered those two id as seceret

```
 bash get_ids_for_repo.sh
REPOSITORY_ID: "R*********g"
CATEGORY_ID: "D**********1"
```

image

**Review by kim201212 — APPROVED** [review]
LGTM!

**Pull request merged**
