### PR TITLE
Add new discord webhook address type

### PR DESCRIPTION
**Pull request by heejin-github**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** #576

**Summary**

---

Add new discord webhook address type.

### CODE REVIEW

**Comment by xellos00** [comment]
@heejin-github 
Can you create an issue for this PR?

**Comment by heejin-github** [comment]
> @heejin-github Can you create an issue for this PR?

created #576

**Review by xellos00 — APPROVED** [review]
LGTM

**Review by gnongs — APPROVED** [review]
LGTM!

**Pull request merged**
