### PR TITLE
Install and start plugin by CLI

### LINKED ISSUE #298: Plugin install feature through CLI
## Checklist
- [X] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

Currently, using VATZ plugins seems a little bit messy.
We have to build VATZ, and VATZ Plugins from source code and execute each processes individually.
So it could be not easy to manage those plugins precisely.

So, I suggest the new CLI command to install plugins that will make a better experience for users.

Due to Golang provides `go install` command by default, it will not too hard to implement `plugin install` command.

Expected user scenario is like below.
1. Assume the user already install VATZ.
2. Execute `./vatz plugin install <PLUGIN_REPO>
3. Then internally VATZ try `go install <PLUGIN_REPO>` from some directory which is defined on VATZ.
4. If the installation is completed, new plugin binary is available on the machine.

After the implementation is completed, the below command will be available.

```
~$ ./vatz plugins install <GITHUB_REPO>
```

N/A

After implementing this issue, it could be possible to start the plugin with VATZ CLI.

---

This issue will be splited into several tasks.
- [ ] Implement `plugin install`
- [ ] Add the new config to store plugin binaries

### PR DESCRIPTION
**Pull request by rootwarp**
### 1. Type of change

Please delete options that are not relevant.

- [x] New feature
- [ ] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)
#307 

close #298 

**Summary**

This PR is inherited from #307.

---

### CODE REVIEW

**Comment by rootwarp** [comment]
Comes from #307

**Comment by xellos00** [comment]
> Comes from #307

Let me try little more and will approve it by tomorrow.

**Comment by xellos00** [comment]
@rootwarp 
every thing is fixed since last comment with feedback that I gave to you. 

1. Create a home directory if there's no .vatz directory under home path
> I confirmed a new folder is created under home if there's no .vatz folder!!

2. Can we put code automatically, get rid of https:// or http?
> I confirmed it's working properly with https

--- 
few more suggestion. 

3. Can we update that message that if user try to install same plugin again?
```
  ./vatz plugin install https://github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status cosmos-status
2022-12-01T22:06:02-06:00 INF Install new plugin https://github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status at /Users/dongyookang/.vatz module=plugin
2022-12-01T22:06:02-06:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status module=plugin
2022-12-01T22:06:04-06:00 INF newWriter /Users/dongyookang/.vatz/vatz.db module=db
2022-12-01T22:06:04-06:00 INF Create DB Instance module=db
2022-12-01T22:06:04-06:00 INF AddPlugin module=db
Error: UNIQUE constraint failed: plugin.name
Usage:
   plugin install [flags]

Examples:
vats plugin install github.com/dsrvlabs/<somewhere> name

Flags:
  -h, --help   help for install

panic: UNIQUE constraint failed: plugin.name

goroutine 1 [running]:
main.main()
        /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/main.go:20 +0x45

``` 

4.  I think we do really need cmd that 
- vatz plugin list
- vatz plugin `plugin-name` status

**Comment by rootwarp** [comment]
@xellos00 Thanks for review 👍 
3. Can we update that warning message that if user try to install same plugin again?
Good. it seems mandatory feature.

6. I think we do really need cmd that ./vatz plugin list that display followings
Sure. `list` command will be really important. It is planned as child issue of #316.

7. How do we see plugin logs when we start plugin with .vatz cmd?
That the problem we faced. As you can see `manager/plugin/plugin.go:90`, I added `TODO` tag for future work.
My rough idea is redirect plugin's log into file, which is retrieved from cli argument.

8. Can we create a unique key like(hash) with repository + version for primary key in DB schema.
It is really awesome idea. it should be added for future work.

**Comment by xellos00** [comment]
> @xellos00 Thanks for review 👍
> 
> 3. Can we update that warning message that if user try to install same plugin again?
>    Good. it seems mandatory feature.
> 4. I think we do really need cmd that ./vatz plugin list that display followings
>    Sure. `list` command will be really important. It is planned as child issue of [CLI for plugin #316](https://github.com/dsrvlabs/vatz/issues/316).
> 5. How do we see plugin logs when we start plugin with .vatz cmd?
>    That the problem we faced. As you can see `manager/plugin/plugin.go:90`, I added `TODO` tag for future work.
>    My rough idea is redirect plugin's log into file, which is retrieved from cli argument.
> 6. Can we create a unique key like(hash) with repository + version for primary key in DB schema.
>    It is really awesome idea. it should be added for future work.

@rootwarp 
Are you going to add warning message for item 3 on above in this issue? or push to next progress?

**Comment by rootwarp** [comment]
@xellos00 It could be better to to that on another issue because for starting related issued in parallel.

**Comment by xellos00** [comment]
> @xellos00 It could be better to to that on another issue because for starting related issued in parallel.

got it!!

**Comment by xellos00** [comment]
# Confirmed

image

**Comment by rootwarp** [comment]
> 

@xellos00 Agree, `vatz plugin status` command should show error message if VATZ is not running.

**Review by xellos00 — APPROVED** [review]

**Comment by rootwarp** [comment]
@dsrvlabs/validator please take look at this.

**Comment by xellos00** [comment]
> @dsrvlabs/validator please take look at this.

I will ping to urge people to review again.

**Comment by xellos00** [comment]
hmmmmmmm, I will ask them on next Monday again.

**Review by gnongs — APPROVED** [review]
LGTM !

**Comment by xellos00** [comment]
@rootwarp 
I am going to merge this, do you still need more feedback on #335?

**Comment by rootwarp** [comment]
> @rootwarp 
> 
> I am going to merge this, do you still need more feedback on #335?

Regarding #355, I will rebase and test again after this PR merged.

**Comment by xellos00** [comment]
> > @rootwarp
> > I am going to merge this, do you still need more feedback on #335?
> 
> @xellos00 Regarding #355, I will rebase and test again after this PR merged.

Cool!!

**Pull request merged**
