### PR TITLE
Update Missed Typos in README.md

### PR DESCRIPTION
**Pull request by xellos00**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [x] others (anything other than above)

---

relate: #394 

Update Missed Typos in README.md

### CODE REVIEW

**Review by meetrick — APPROVED** [review]
LGTM

**Review by wellofyuba — APPROVED** [review]
LGTM

**Review by wellofyuba — APPROVED** [review]
LGTM again.

**Review by kim201212 — APPROVED** [review]
LGTM 👍

**Pull request merged**
