### PR TITLE
CLI - Stop Plugin

### LINKED ISSUE #386: CLI - Stop plugin
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [x] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Describe alternatives you've considered**
N/A

### **Additional context**
N/A

### PR DESCRIPTION
**Pull request by rootwarp**
### 1. Type of change

Please delete options that are not relevant.

- [X] New feature
- [ ] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)

close #386 

**Summary**

Stop a running plugin by CLI.

Testing steps.

```
# Start VATZ first.
rootwarp@mindhack ~/g/d/vatz stop! > ./vatz start

# Install a plugin
rootwarp@mindhack ~/g/d/vatz stop > ./vatz plugin install https://github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status cosmos-status

# Run a plugin
rootwarp@mindhack ~/g/d/vatz stop > ./vatz plugin start --plugin cosmos-status --args "--valoperAddr=cosmosvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02rmvmsu" --log ./status.log

# Stop the plugin
rootwarp@mindhack ~/g/d/vatz stop > ./vatz plugin stop --plugin cosmos-status
```

---

### CODE REVIEW

**Comment by rootwarp** [comment]
```
Test Coverage script will be here
?       github.com/dsrvlabs/vatz        [no test files]
ok      github.com/dsrvlabs/vatz/cmd    2.501s  coverage: 15.5% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.031s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.022s  coverage: 91.2% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.007s  coverage: 7.8% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       0.011s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.016s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 2.912s  coverage: 69.2% of statements
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/rpc    1.009s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.010s  coverage: 50.0% of statements
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=stop' -X 'github.com/dsrvlabs/vatz/utils.Commit=c3ea2d7'" -v
github.com/dsrvlabs/vatz
```

**Review by heejin-github — APPROVED** [review]
Tested. LGTM!
```
heejin@home-server:~/work/vatz/vatz/bin$ vatz plugin start -p vatz_disk_monitor
2023-01-17T02:44:38Z INF Start plugin vatz_disk_monitor  module=plugin
2023-01-17T02:44:38Z INF Plugin log redirect to /home/heejin/.vatz/vatz_disk_monitor.log module=plugin
2023-01-17T02:44:38Z INF Start plugin vatz_disk_monitor module=plugin
2023-01-17T02:44:38Z INF newReader /home/heejin/.vatz/vatz.db module=db
2023-01-17T02:44:38Z INF Create DB Instance module=db
2023-01-17T02:44:38Z INF Get vatz_disk_monitor module=db

heejin@home-server:~/work/vatz/vatz/bin$ vatz plugin status
***** Plugin status *****
1: vatz_disk_monitor [OK]

heejin@home-server:~/work/vatz/vatz/bin$ vatz plugin stop -p vatz_disk_monitor
2023-01-17T02:45:01Z INF Stop plugin vatz_disk_monitor module=plugin
2023-01-17T02:45:01Z INF Stop plugin vatz_disk_monitor module=plugin
2023-01-17T02:45:01Z INF Find Process vatz_disk_monitor module=plugin

heejin@home-server:~/work/vatz/vatz/bin$ vatz plugin status
***** Plugin status *****
1: vatz_disk_monitor [FAIL]

```

**Comment by xellos00** [comment]
@dsrvlabs/validator 
Please, Review #387

**Review by meetrick — APPROVED** [review]
LGTM

**Pull request merged**
