### PR TITLE
Fix. config instance should be loaded before execute CLI.

### LINKED ISSUE #439: VATZ CI Error on `uninstall` & `enable`
### Checklist
- [x] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

1. Since Config register home_path, there's error on for following  CI command so tested with previous version of VATZ 
- `uninstall`
- `enable`

```
 git fetch origin pull/428/head:ISSUE-388-RES
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 22 (delta 13), reused 22 (delta 13), pack-reused 0
Unpacking objects: 100% (22/22), 9.71 KiB | 523.00 KiB/s, done.
From https://github.com/dsrvlabs/vatz
 * [new ref]         refs/pull/428/head -> ISSUE-388-RES
 dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   main ±✚
 git checkout ISSUE-388-RES                  
A       .idea/.gitignore
Switched to branch 'ISSUE-388-RES'
 ./vatz plugin list                  
2023-05-21T21:27:48-05:00 INF List plugins module=plugin
2023-05-21T21:27:48-05:00 INF Create DB Instance module=db
2023-05-21T21:27:48-05:00 INF List module=plugin
2023-05-21T21:27:48-05:00 INF List module=db
+------+------------+--------------+------------+---------+
| NAME | IS ENABLED | INSTALL DATE | REPOSITORY | VERSION |
+------+------------+--------------+------------+---------+
+------+------------+--------------+------------+---------+
 dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   ISSUE-388-RES ±✚
 ./vatz plugin install github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor cpu-monitor1
2023-05-21T21:31:38-05:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor at /Users/dongyookang/.vatz module=plugin
2023-05-21T21:31:38-05:00 INF Create DB Instance module=db
2023-05-21T21:31:38-05:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor module=plugin
2023-05-21T21:31:41-05:00 INF AddPlugin module=db
 dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   ISSUE-388-RES ±✚
 ./vatz plugin enable cpu-monitor1 false                                                       
2023-05-21T21:31:50-05:00 INF enable installed plugin cpu-monitor1 at /Users/dongyookang/.vatz module=plugin
2023-05-21T21:31:50-05:00 INF Create DB Instance module=db
2023-05-21T21:31:50-05:00 INF UpdatePlugin module=db
2023-05-21T21:31:50-05:00 INF Plugin cpu-monitor1 has been updated: disabled. module=db
 dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   ISSUE-388-RES ±✚
 ./vatz plugin list                                                                                            
2023-05-21T21:32:06-05:00 INF List plugins module=plugin
2023-05-21T21:32:06-05:00 INF Create DB Instance module=db
2023-05-21T21:32:06-05:00 INF List module=plugin
2023-05-21T21:32:06-05:00 INF List module=db
+--------------+------------+---------------------+-------------------------------------------------------------+---------+
| NAME         | IS ENABLED | INSTALL DATE        | REPOSITORY                                                  | VERSION |
+--------------+------------+---------------------+-------------------------------------------------------------+---------+
| cpu-monitor1 | false      | 2023-05-21 21:31:41 | github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor | latest  |
+--------------+------------+---------------------+-------------------------------------------------------------+---------+

```

2. Switched to Current VATZ `main`

```
 clear
 dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   main ±✚
 make build
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=main' -X 'github.com/dsrvlabs/vatz/utils.Commit=85df83a'" -v
github.com/dsrvlabs/vatz/manager/config
github.com/dsrvlabs/vatz/manager/api
github.com/dsrvlabs/vatz/manager/types
github.com/dsrvlabs/vatz/utils
github.com/dsrvlabs/vatz/manager/plugin
github.com/dsrvlabs/vatz/manager/dispatcher
github.com/dsrvlabs/vatz/monitoring/prometheus
github.com/dsrvlabs/vatz/manager/healthcheck
github.com/dsrvlabs/vatz/manager/executor
github.com/dsrvlabs/vatz/rpc
github.com/dsrvlabs/vatz/cmd
github.com/dsrvlabs/vatz
 dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   main ±✚
 ./vatz init       
2023-05-21T21:36:47-05:00 INF init module=main
2023-05-21T21:36:47-05:00 INF create file default.yaml module=main
2023-05-21T21:36:47-05:00 INF home path ~/.vatz module=main
2023-05-21T21:36:47-05:00 INF Load Config default.yaml module=config
2023-05-21T21:36:47-05:00 INF Plugin dir /Users/dongyookang/.vatz module=main
2023-05-21T21:36:47-05:00 INF Create DB Instance module=db
2023-05-21T21:36:47-05:00 INF initDB /Users/dongyookang/.vatz/vatz.db module=db
2023-05-21T21:36:47-05:00 INF Remove old DB file module=db
2023-05-21T21:36:47-05:00 INF Create new DB file module=db
2023-05-21T21:36:47-05:00 INF Create DB Instance module=db
 dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   main ±✚
 ./vatz plugin install github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor cpu-monitor1
2023-05-21T21:37:17-05:00 INF Load Config default.yaml module=config
2023-05-21T21:37:17-05:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor at /Users/dongyookang/.vatz module=plugin
2023-05-21T21:37:17-05:00 INF Create DB Instance module=db
2023-05-21T21:37:17-05:00 INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor module=plugin
2023-05-21T21:37:19-05:00 INF AddPlugin module=db
 dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   main ±✚
 ./vatz plugin uninstall cpu-monitor1                                                          
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1006a7b20]

goroutine 1 [running]:
github.com/dsrvlabs/vatz/cmd.glob..func5(0x100f32a60?, {0xc000119ed0, 0x1, 0x1?})
        /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/cmd/plugin.go:117 +0x40
github.com/spf13/cobra.(*Command).execute(0x100f32a60, {0xc000119eb0, 0x1, 0x1})
        /Users/dongyookang/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000274780)
        /Users/dongyookang/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x100edc088?)
        /Users/dongyookang/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918 +0x19
main.main()
        /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/main.go:19 +0x1e
 ✘ dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   main ±✚
 
 ./vatz plugin enable cpu-monitor1 false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1006a84a0]

goroutine 1 [running]:
github.com/dsrvlabs/vatz/cmd.glob..func10(0x100f331e0?, {0xc00007d660, 0x2, 0x2?})
        /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/cmd/plugin.go:201 +0x40
github.com/spf13/cobra.(*Command).execute(0x100f331e0, {0xc00007d620, 0x2, 0x2})
        /Users/dongyookang/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000264780)
        /Users/dongyookang/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x100edc088?)
        /Users/dongyookang/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918 +0x19
main.main()
        /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/main.go:19 +0x1e
 ✘ dongyookang DK 😎   ~/ffplay/GolandProjects/dsrvlabs/vatz   main ±✚
 

``` 

working clear as plugin update enable ture/false and uninstall

### PR DESCRIPTION
**Pull request by rootwarp**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Enhancement
- [x] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)

close #439 

**Summary**

Fix `uninstall` and `status` command.
`PreRunE` is required on cobra command to instantiate config instance before running the command.

---

### CODE REVIEW

**Comment by rootwarp** [comment]
# Before

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa86ce0]

goroutine 1 [running]:
github.com/dsrvlabs/vatz/cmd.glob..func10(0x124df00?, {0xc0002a64a0, 0x2, 0x2?})
        /home/rootwarp/git/dsrv/vatz/cmd/plugin.go:201 +0x40
github.com/spf13/cobra.(*Command).execute(0x124df00, {0xc0002a6460, 0x2, 0x2})
        /home/rootwarp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002a8f00)
        /home/rootwarp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/rootwarp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/rootwarp/git/dsrv/vatz/main.go:19 +0x1e
```


```
rootwarp@mindhack ~/g/d/vatz issue#439! > ./vatz plugin uninstall cpu-monitor1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa86360]

goroutine 1 [running]:
github.com/dsrvlabs/vatz/cmd.glob..func5(0x124d780?, {0xc00031a510, 0x1, 0x1?})
        /home/rootwarp/git/dsrv/vatz/cmd/plugin.go:117 +0x40
github.com/spf13/cobra.(*Command).execute(0x124d780, {0xc00031a4f0, 0x1, 0x1})
        /home/rootwarp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000328f00)
        /home/rootwarp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/rootwarp/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/rootwarp/git/dsrv/vatz/main.go:19 +0x1e
rootwarp@mindhack ~/g/d/vatz issue#439! >
```

**Comment by rootwarp** [comment]
# Coverage

```
rootwarp@mindhack ~/g/d/vatz issue#439 > make coverage
?       github.com/dsrvlabs/vatz        [no test files]
ok      github.com/dsrvlabs/vatz/cmd    2.777s  coverage: 19.8% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.029s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.008s  coverage: 79.4% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.045s  coverage: 7.8% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       0.028s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.009s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 2.594s  coverage: 50.6% of statements
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  0.034s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    1.010s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.006s  coverage: 7.1% of statements
```

**Review by xellos00 — APPROVED** [review]

**Comment by gnongs** [comment]
```sh
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # git branch
  main
* pr-441
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # make build
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=main' -X 'github.com/dsrvlabs/vatz/utils.Commit=85df83a'" -v
go: downloading github.com/dsrvlabs/vatz-proto v0.0.0-20220908182122-4c28400b195f
go: downloading github.com/jedib0t/go-pretty/v6 v6.4.3
go: downloading github.com/shirou/gopsutil v3.21.11+incompatible
go: downloading golang.org/x/net v0.7.0
....
github.com/dsrvlabs/vatz
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz init
2023-05-23T01:30:33Z INF init module=main
2023-05-23T01:30:33Z INF create file default.yaml module=main
2023-05-23T01:30:33Z INF home path ~/.vatz module=main
2023-05-23T01:30:33Z INF Load Config default.yaml module=config
2023-05-23T01:30:33Z INF Plugin dir /root/.vatz module=main
2023-05-23T01:30:33Z INF initDB /root/.vatz/vatz.db module=db
2023-05-23T01:30:33Z INF Remove old DB file module=db
2023-05-23T01:30:33Z INF Create new DB file module=db
2023-05-23T01:30:33Z INF Create DB Instance module=db
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz plugin install github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor cpu-monitor
2023-05-23T01:33:28Z INF Load Config default.yaml module=config
2023-05-23T01:33:28Z INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor at /root/.vatz module=plugin
2023-05-23T01:33:28Z INF Create DB Instance module=db
2023-05-23T01:33:28Z INF Install new plugin github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor module=plugin
2023-05-23T01:33:36Z INF AddPlugin module=db
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz plugin list
2023-05-23T01:33:50Z INF Load Config default.yaml module=config
2023-05-23T01:33:50Z INF List plugins module=plugin
2023-05-23T01:33:50Z INF Create DB Instance module=db
2023-05-23T01:33:50Z INF List module=plugin
2023-05-23T01:33:50Z INF List module=db
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
| NAME        | IS ENABLED | INSTALL DATE        | REPOSITORY                                                  | VERSION |
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
| cpu-monitor | true       | 2023-05-23 01:33:36 | github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor | latest  |
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
```
```sh
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz plugin enable cpu-monitor false
2023-05-23T01:35:38Z INF Load Config default.yaml module=config
2023-05-23T01:35:38Z INF enable installed plugin cpu-monitor at /root/.vatz module=plugin
2023-05-23T01:35:38Z INF Create DB Instance module=db
2023-05-23T01:35:38Z INF UpdatePlugin module=db
2023-05-23T01:35:38Z INF Plugin cpu-monitor has been updated: disabled. module=db
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz plugin list
2023-05-23T01:35:46Z INF Load Config default.yaml module=config
2023-05-23T01:35:46Z INF List plugins module=plugin
2023-05-23T01:35:46Z INF Create DB Instance module=db
2023-05-23T01:35:46Z INF List module=plugin
2023-05-23T01:35:46Z INF List module=db
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
| NAME        | IS ENABLED | INSTALL DATE        | REPOSITORY                                                  | VERSION |
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
| cpu-monitor | false      | 2023-05-23 01:33:36 | github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor | latest  |
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz plugin enable cpu-monitor true
2023-05-23T01:36:28Z INF Load Config default.yaml module=config
2023-05-23T01:36:28Z INF enable installed plugin cpu-monitor at /root/.vatz module=plugin
2023-05-23T01:36:28Z INF Create DB Instance module=db
2023-05-23T01:36:28Z INF UpdatePlugin module=db
2023-05-23T01:36:28Z INF Plugin cpu-monitor has been updated: enabled. module=db
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz plugin list
2023-05-23T01:36:33Z INF Load Config default.yaml module=config
2023-05-23T01:36:33Z INF List plugins module=plugin
2023-05-23T01:36:33Z INF Create DB Instance module=db
2023-05-23T01:36:33Z INF List module=plugin
2023-05-23T01:36:33Z INF List module=db
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
| NAME        | IS ENABLED | INSTALL DATE        | REPOSITORY                                                  | VERSION |
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
| cpu-monitor | true       | 2023-05-23 01:33:36 | github.com/dsrvlabs/vatz-plugin-sysutil/plugins/cpu_monitor | latest  |
+-------------+------------+---------------------+-------------------------------------------------------------+---------+
```
```sh
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz plugin uninstall cpu-monitor
2023-05-23T01:37:03Z INF Load Config default.yaml module=config
2023-05-23T01:37:03Z INF Uninstall a plugin cpu-monitor from /root/.vatz module=plugin
2023-05-23T01:37:03Z INF Create DB Instance module=db
2023-05-23T01:37:03Z INF List module=plugin
2023-05-23T01:37:03Z INF Find Process cpu-monitor module=plugin
2023-05-23T01:37:03Z INF Get cpu-monitor module=plugin
2023-05-23T01:37:03Z INF Get cpu-monitor module=db
2023-05-23T01:37:03Z INF DeletePlugin module=db
root@ibc-mainnet-relayer2-hetzner-fsn1 ~/git/vatz # ./vatz plugin list
2023-05-23T01:37:09Z INF Load Config default.yaml module=config
2023-05-23T01:37:09Z INF List plugins module=plugin
2023-05-23T01:37:09Z INF Create DB Instance module=db
2023-05-23T01:37:09Z INF List module=plugin
2023-05-23T01:37:09Z INF List module=db
+------+------------+--------------+------------+---------+
| NAME | IS ENABLED | INSTALL DATE | REPOSITORY | VERSION |
+------+------------+--------------+------------+---------+
+------+------------+--------------+------------+---------+
```

**Review by gnongs — APPROVED** [review]
LGTM!

**Comment by skonhwang** [comment]
## build
```
hwangseungkon@skonhwang-MacBookPro ~/dsrv/2022/vatz/vatz $ git branch
* 441
  main
hwangseungkon@skonhwang-MacBookPro ~/dsrv/2022/vatz/vatz $ make build
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=441' -X 'github.com/dsrvlabs/vatz/utils.Commit=749f901'" -v
go: downloading github.com/jedib0t/go-pretty/v6 v6.4.3
go: downloading google.golang.org/grpc v1.50.1
go: downloading github.com/PagerDuty/go-pagerduty v1.6.0
go: downloading github.com/mattn/go-sqlite3 v1.14.16
go: downloading github.com/stretchr/objx v0.5.0
go: downloading github.com/tklauser/go-sysconf v0.3.11
go: downloading github.com/google/go-querystring v1.0.0
google.golang.org/protobuf/internal/flags
google.golang.org/protobuf/internal/set
google.golang.org/grpc/attributes
google.golang.org/grpc/serviceconfig
github.com/rivo/uniseg
google.golang.org/protobuf/internal/pragma
google.golang.org/grpc/encoding
google.golang.org/grpc/internal/buffer
google.golang.org/grpc/internal/grpcsync
google.golang.org/grpc/backoff
google.golang.org/grpc/internal/grpcrand
google.golang.org/grpc/keepalive
google.golang.org/grpc/tap
golang.org/x/text/transform
golang.org/x/net/context
golang.org/x/net/internal/timeseries
google.golang.org/grpc/internal/grpclog
google.golang.org/protobuf/internal/detrand
google.golang.org/protobuf/internal/version
google.golang.org/grpc/metadata
google.golang.org/grpc/internal/backoff
google.golang.org/grpc/codes
google.golang.org/grpc/grpclog
google.golang.org/protobuf/internal/errors
google.golang.org/grpc/internal/envconfig
golang.org/x/text/unicode/bidi
golang.org/x/text/unicode/norm
google.golang.org/grpc/internal/balancerload
google.golang.org/grpc/internal/grpcutil
golang.org/x/net/http2/hpack
google.golang.org/protobuf/encoding/protowire
google.golang.org/grpc/stats
golang.org/x/net/trace
golang.org/x/sys/unix
google.golang.org/grpc/connectivity
google.golang.org/protobuf/reflect/protoreflect
google.golang.org/grpc/internal/credentials
google.golang.org/grpc/internal/syscall
github.com/rs/zerolog/internal/json
github.com/google/go-querystring/query
github.com/robfig/cron/v3
github.com/stretchr/objx
github.com/stretchr/testify/assert
github.com/PagerDuty/go-pagerduty
golang.org/x/text/secure/bidirule
google.golang.org/protobuf/internal/encoding/messageset
google.golang.org/protobuf/internal/strs
google.golang.org/protobuf/internal/genid
google.golang.org/protobuf/internal/order
google.golang.org/protobuf/internal/encoding/text
google.golang.org/protobuf/reflect/protoregistry
google.golang.org/protobuf/runtime/protoiface
google.golang.org/protobuf/internal/descfmt
google.golang.org/protobuf/proto
google.golang.org/protobuf/internal/encoding/defval
google.golang.org/protobuf/internal/descopts
google.golang.org/protobuf/internal/encoding/json
github.com/grpc-ecosystem/grpc-gateway/v2/utilities
golang.org/x/net/idna
github.com/mattn/go-runewidth
github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule
google.golang.org/protobuf/encoding/prototext
google.golang.org/protobuf/internal/filedesc
github.com/jedib0t/go-pretty/v6/text
github.com/mattn/go-isatty
github.com/mattn/go-colorable
github.com/mattn/go-sqlite3
github.com/rs/zerolog
github.com/shirou/gopsutil/internal/common
github.com/tklauser/go-sysconf
golang.org/x/net/http/httpguts
github.com/prometheus/procfs
golang.org/x/net/http2
github.com/stretchr/testify/mock
github.com/jedib0t/go-pretty/v6/table
github.com/shirou/gopsutil/cpu
github.com/shirou/gopsutil/mem
google.golang.org/protobuf/internal/encoding/tag
google.golang.org/protobuf/internal/impl
google.golang.org/protobuf/encoding/protojson
github.com/rs/zerolog/log
github.com/dsrvlabs/vatz/manager/config
github.com/shirou/gopsutil/net
github.com/spf13/pflag
github.com/fsnotify/fsnotify
github.com/mitchellh/mapstructure
github.com/spf13/cobra
golang.org/x/text/runes
github.com/spf13/afero
github.com/magiconair/properties
github.com/spf13/viper/internal/encoding/javaproperties
github.com/spf13/viper
github.com/shirou/gopsutil/process
google.golang.org/protobuf/internal/filetype
google.golang.org/protobuf/runtime/protoimpl
google.golang.org/protobuf/types/known/timestamppb
google.golang.org/protobuf/types/known/emptypb
google.golang.org/protobuf/types/known/durationpb
google.golang.org/protobuf/types/known/anypb
google.golang.org/protobuf/types/known/structpb
google.golang.org/protobuf/types/descriptorpb
github.com/golang/protobuf/ptypes/timestamp
github.com/golang/protobuf/ptypes/duration
google.golang.org/protobuf/types/known/fieldmaskpb
github.com/golang/protobuf/ptypes/any
google.golang.org/genproto/googleapis/rpc/status
google.golang.org/genproto/googleapis/api/httpbody
google.golang.org/protobuf/types/known/wrapperspb
google.golang.org/genproto/protobuf/field_mask
google.golang.org/protobuf/reflect/protodesc
google.golang.org/genproto/googleapis/api/annotations
github.com/golang/protobuf/proto
google.golang.org/grpc/encoding/proto
google.golang.org/grpc/credentials
google.golang.org/grpc/binarylog/grpc_binarylog_v1
github.com/prometheus/client_model/go
github.com/golang/protobuf/jsonpb
github.com/golang/protobuf/ptypes
github.com/matttproud/golang_protobuf_extensions/pbutil
google.golang.org/grpc/credentials/insecure
google.golang.org/grpc/internal/channelz
google.golang.org/grpc/peer
google.golang.org/grpc/internal/status
github.com/prometheus/client_golang/prometheus/internal
github.com/prometheus/common/expfmt
google.golang.org/grpc/status
google.golang.org/grpc/internal/binarylog
google.golang.org/grpc/channelz
google.golang.org/grpc/internal/pretty
google.golang.org/grpc/resolver
github.com/prometheus/client_golang/prometheus
google.golang.org/grpc/internal
google.golang.org/grpc/internal/metadata
google.golang.org/grpc/balancer/grpclb/state
google.golang.org/grpc/internal/resolver/passthrough
google.golang.org/grpc/internal/transport/networktype
google.golang.org/grpc/internal/resolver/dns
google.golang.org/grpc/internal/resolver/unix
google.golang.org/grpc/internal/transport
google.golang.org/grpc/balancer
google.golang.org/grpc/balancer/base
google.golang.org/grpc/internal/serviceconfig
google.golang.org/grpc/internal/resolver
google.golang.org/grpc/balancer/roundrobin
google.golang.org/grpc/internal/balancer/gracefulswitch
github.com/prometheus/client_golang/prometheus/collectors
github.com/prometheus/client_golang/prometheus/promhttp
google.golang.org/grpc
google.golang.org/grpc/health/grpc_health_v1
google.golang.org/grpc/reflection/grpc_reflection_v1alpha
github.com/dsrvlabs/vatz-proto/plugin/v1
github.com/dsrvlabs/vatz-proto/manager/v1
github.com/grpc-ecosystem/grpc-gateway/v2/runtime
google.golang.org/grpc/health
github.com/dsrvlabs/vatz/manager/types
github.com/dsrvlabs/vatz/utils
google.golang.org/grpc/reflection
github.com/dsrvlabs/vatz/manager/api
github.com/dsrvlabs/vatz/monitoring/prometheus
github.com/dsrvlabs/vatz/manager/dispatcher
github.com/dsrvlabs/vatz/manager/executor
github.com/dsrvlabs/vatz/manager/healthcheck
github.com/dsrvlabs/vatz-proto/rpc/v1
github.com/dsrvlabs/vatz/rpc
github.com/dsrvlabs/vatz/manager/plugin
github.com/dsrvlabs/vatz/cmd
github.com/dsrvlabs/vatz
```
## init
```
hwangseungkon@skonhwang-MacBookPro ~/dsrv/2022/vatz/vatz $ ./vatz init
2023-05-23T10:41:13+09:00 INF init module=main
2023-05-23T10:41:13+09:00 INF create file default.yaml module=main
2023-05-23T10:41:13+09:00 INF home path ~/.vatz module=main
2023-05-23T10:41:13+09:00 INF Load Config default.yaml module=config
2023-05-23T10:41:13+09:00 INF Plugin dir /Users/hwangseungkon/.vatz module=main
2023-05-23T10:41:13+09:00 INF initDB /Users/hwangseungkon/.vatz/vatz.db module=db
2023-05-23T10:41:13+09:00 INF Remove old DB file module=db
2023-05-23T10:41:13+09:00 INF Create new DB file module=db
2023-05-23T10:41:13+09:00 INF Create DB Instance module=db
```
## enable cpu-monitor
```
hwangseungkon@skonhwang-MacBookPro ~/dsrv/2022/vatz/vatz $ ./vatz plugin enable cpu-monitor false
2023-05-23T10:41:17+09:00 INF Load Config default.yaml module=config
2023-05-23T10:41:17+09:00 INF enable installed plugin cpu-monitor at /Users/hwangseungkon/.vatz module=plugin
2023-05-23T10:41:17+09:00 INF Create DB Instance module=db
2023-05-23T10:41:17+09:00 INF UpdatePlugin module=db
2023-05-23T10:41:17+09:00 INF Plugin cpu-monitor has been updated: disabled. module=db
```
## plugin list
```
hwangseungkon@skonhwang-MacBookPro ~/dsrv/2022/vatz/vatz $ ./vatz plugin list
2023-05-23T10:41:31+09:00 INF Load Config default.yaml module=config
2023-05-23T10:41:31+09:00 INF List plugins module=plugin
2023-05-23T10:41:31+09:00 INF Create DB Instance module=db
2023-05-23T10:41:31+09:00 INF List module=plugin
2023-05-23T10:41:31+09:00 INF List module=db
+------+------------+--------------+------------+---------+
| NAME | IS ENABLED | INSTALL DATE | REPOSITORY | VERSION |
+------+------------+--------------+------------+---------+
+------+------------+--------------+------------+---------+
```
LGTM

**Pull request merged**
