### PR TITLE
Add new official icons for VATZ 

### LINKED ISSUE #405: Follow up progress for VATZ's official icons
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [x] others(etc. e.g, documentation, project policy management)

---

image

Current icon of VATZ project isn't designed for the VATZ project. 
As we discussed in weekly meeting, we requested VATZ on official icons to  @Jihoo-Designer
I will share this issue to @Jihoo-Designer

I will keep update progress about icon, but its priority is low and can't push @Jihoo-Designer.

### PR DESCRIPTION
**Pull request by xellos00**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

close #405 

**Summary**

Add a new official icons from @Jihoo-Designer and add Ascii mark on CLI command `version`

image

```
 dongyookang DK 🚀   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-405 ±
 ./vatz version
                                                                        
   @@@@@@@@@@@@@@@         @@@@@@@@@@@@@@@@@@@                  
    #@@@@@@@@@@@@@@@           @@@@@@@@@@@@@.                   
      @@@@@@@@@@@@@@@              &@@@@@@@                     
       @@@@@@@@@@@@@@@&            ,@@@@@.                      
         @@@@@@@@@@@@@@@           ,@@@@                        
          @@@@@@@@@@@@@@@(         ,@@/                         
           .@@@@@@@@@@@@@@@        ,@                           
             @@@@@@@@@@@@@@@.      .                            
              *@@@@@@@@@@@@@@@                                  
                @@@@@@@@@@@@@@@.                                
                 &@@@@@@@@@@@@@@                                
                   @@@@@@@@@@@                                  
                    @@@@@@@@%                                   
                      @@@@@                                     
                       @@*    VATZ dsrv labs Co., Ltd. 

VATZ Version: ISSUE-405-51b4123

```

### CODE REVIEW

**Comment by xellos00** [comment]
image

**Review by kim201212 — APPROVED** [review]
LGTM 🚀

**Review by rootwarp — APPROVED** [review]
LGTM

**Review by meetrick — COMMENTED** [review]
LGTM

**Pull request merged**
