### PR TITLE
fix panic message when all CLI commands fails.

### PR DESCRIPTION
**Pull request by xellos00**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Enhancement
- [x] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)
realted: #469 

**Summary**
as issue 
- #469, pretty much every CLI commands panics when there's error. 
so it hide those panic messages 

---

```
 dongyookang DK 🔑   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-469
 make coverage
fatal: No names found, cannot describe anything.
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    14.427s coverage: 23.5% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.499s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.811s  coverage: 77.8% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     1.602s  coverage: 7.1% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       1.755s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    1.449s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 19.831s coverage: 51.1% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  1.127s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    2.299s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.950s  coverage: 7.1% of statements
 dongyookang DK 🔑   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-469
 

```

### CODE REVIEW

**Review by meetrick — APPROVED** [review]
LGTM

**Comment by xellos00** [comment]
# sample 
```
 dongyookang DK 🔑   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-469
 ./vatz plugin list
false2023-06-16T00:34:37-05:00 INF Load Config default.yaml module=config
Error: open default.yaml: no such file or directory
Usage:
   plugin list [flags]

Examples:
vatz plugin list

Flags:
  -h, --help   help for list

2023-06-16T00:34:37-05:00 ERR Please, Check config file default.yaml path or initialize VATZ with command `vatz init` to create config file `default.yaml`. module=config
 dongyookang DK 🔑   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-469
 
```

**Review by gnongs — APPROVED** [review]
LGTM!

```sh
 GNONG  ~/workspace/dsrv/vatz   pr-473  ./vatz fkdlajfie
Error: unknown command "fkdlajfie" for ""
Run ' --help' for usage.
2023-06-16T15:03:12+09:00 ERR VATZ CLI command Error: unknown command "fkdlajfie" for ""
 GNONG  ~/workspace/dsrv/vatz   pr-473  ./vatz init --a4123
Error: unknown flag: --a4123
Usage:
   init [flags]

Flags:
  -a, --all             Create config yaml with all default setting of official plugins.
  -h, --help            help for init
  -p, --home string     Home directory of VATZ (default "~/.vatz")
  -o, --output string   New config file to create (default "default.yaml")

2023-06-16T15:04:16+09:00 ERR VATZ CLI command Error: unknown flag: --a4123
 GNONG  ~/workspace/dsrv/vatz   pr-473  ./vatz init --plugin ifenalifnelia
Error: unknown flag: --plugin
Usage:
   init [flags]

Flags:
  -a, --all             Create config yaml with all default setting of official plugins.
  -h, --help            help for init
  -p, --home string     Home directory of VATZ (default "~/.vatz")
  -o, --output string   New config file to create (default "default.yaml")

2023-06-16T15:03:31+09:00 ERR VATZ CLI command Error: unknown flag: --plugin
```

**Review by kim201212 — COMMENTED** [review]
```shell

 hg  ~/workspace/test/vatz  ➦ b7efee0  ./vatz plugin list
2023-06-16T15:23:48+09:00 INF Load Config default.yaml module=config
Error: open default.yaml: no such file or directory
Usage:
   plugin list [flags]

Examples:
vatz plugin list

Flags:
  -h, --help   help for list

2023-06-16T15:23:48+09:00 ERR Please, Check config file default.yaml path or initialize VATZ with command `vatz init` to create config file `default.yaml`. module=config
 hg  ~/workspace/test/vatz  ➦ b7efee0  ./vatz init --aal
Error: unknown flag: --aal
Usage:
   init [flags]

Flags:
  -a, --all             Create config yaml with all default setting of official plugins.
  -h, --help            help for init
  -p, --home string     Home directory of VATZ (default "~/.vatz")
  -o, --output string   New config file to create (default "default.yaml")

2023-06-16T15:23:59+09:00 ERR VATZ CLI command Error: unknown flag: --aal
 hg  ~/workspace/test/vatz  ➦ b7efee0  ./vatz init --all
2023-06-16T15:24:06+09:00 INF init module=main
2023-06-16T15:24:06+09:00 INF home path ~/.vatz module=main
2023-06-16T15:24:06+09:00 INF create file default.yaml module=main
2023-06-16T15:24:06+09:00 INF Load Config default.yaml module=config
2023-06-16T15:24:06+09:00 INF Plugin dir /Users/hg/.vatz module=main
2023-06-16T15:24:06+09:00 INF initDB /Users/hg/.vatz/vatz.db module=db
2023-06-16T15:24:06+09:00 INF Remove old DB file module=db
2023-06-16T15:24:06+09:00 INF Create new DB file module=db
2023-06-16T15:24:06+09:00 INF Create DB Instance module=db
 hg  ~/workspace/test/vatz  ➦ b7efee0 

```

**Review by kim201212 — APPROVED** [review]
LGTM!

**Pull request merged**
