### PR TITLE
Align log format

### PR DESCRIPTION
**Pull request by heejin-github**
keep the same log format between stdout and file output.

### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

Related: #380 

**Summary**

---

### CODE REVIEW

**Review by rootwarp — APPROVED** [review]
Tested. LGTM 👍

**Comment by xellos00** [comment]
@heejin-github 

I Confirmed our common logs is formatted as below
image
image

Are you trying to cover this part as well, or will be covered in another issue? 
```
 make test    
# github.com/dsrvlabs/vatz/manager/plugin.test
ld: warning: -no_pie is deprecated when targeting new OS versions
# github.com/dsrvlabs/vatz/cmd.test
ld: warning: -no_pie is deprecated when targeting new OS versions
?       github.com/dsrvlabs/vatz        [no test files]
=== RUN   TestInitCmd
{"level":"info","module":"main","time":"2023-01-16T10:10:20-06:00","message":"init"}
{"level":"info","module":"main","time":"2023-01-16T10:10:20-06:00","message":"create file default.yaml"}
{"level":"info","module":"main","time":"2023-01-16T10:10:20-06:00","message":"init"}
{"level":"info","module":"main","time":"2023-01-16T10:10:20-06:00","message":"create file hello.yaml"}
--- PASS: TestInitCmd (0.00s)
=== RUN   TestPluginInstall
{"level":"info","module":"plugin","time":"2023-01-16T10:10:20-06:00","message":"Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status at /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/cmd"}
{"level":"info","module":"plugin","time":"2023-01-16T10:10:20-06:00","message":"Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status"}
{"level":"info","module":"db","time":"2023-01-16T10:10:24-06:00","message":"newWriter /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/cmd/vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:10:24-06:00","message":"Create DB Instance"}
{"level":"info","module":"db","time":"2023-01-16T10:10:24-06:00","message":"AddPlugin"}
--- PASS: TestPluginInstall (4.38s)
PASS
ok      github.com/dsrvlabs/vatz/cmd    (cached)
testing: warning: no tests to run
PASS
ok      github.com/dsrvlabs/vatz/manager/api    (cached) [no tests to run]
=== RUN   TestDefaultConfig
--- PASS: TestDefaultConfig (0.00s)
=== RUN   TestOverrideDefaultValues
--- PASS: TestOverrideDefaultValues (0.00s)
=== RUN   TestURLConfig
--- PASS: TestURLConfig (0.00s)
=== RUN   TestNotExistConfigFile
{"level":"info","module":"config","time":"2023-01-16T10:09:48-06:00","message":"Load Config not_existing_file.yaml"}
--- PASS: TestNotExistConfigFile (0.00s)
=== RUN   TestInvalidYAMLFormat
{"level":"info","module":"config","time":"2023-01-16T10:09:48-06:00","message":"Load Config default.yaml"}
{"level":"error","module":"config","time":"2023-01-16T10:09:48-06:00","message":"parseYAML Error: yaml: line 3: mapping values are not allowed in this context"}
--- PASS: TestInvalidYAMLFormat (0.00s)
=== RUN   TestGetConfig
{"level":"info","module":"config","time":"2023-01-16T10:09:48-06:00","message":"Load Config default.yaml"}
--- PASS: TestGetConfig (0.00s)
PASS
ok      github.com/dsrvlabs/vatz/manager/config (cached)
=== RUN   TestMessageHandler
--- PASS: TestMessageHandler (0.00s)
PASS
ok      github.com/dsrvlabs/vatz/manager/dispatcher     (cached)
=== RUN   TestExecutorSuccess
Status {{0 0} {{map[] true}} map[unittest_plugin127.0.0.110002:0xc000122318] 0}
    executor_test.go:104: PASS: Execute(*context.emptyCtx,*v1.ExecuteRequest,[]grpc.CallOption)
--- PASS: TestExecutorSuccess (0.00s)
=== RUN   TestExecutorFailure
Status {{0 0} {{map[] true}} map[unittest_plugin0:0xc000122340] 0}
    executor_test.go:216: PASS: Execute(*context.emptyCtx,*v1.ExecuteRequest,[]grpc.CallOption)
Status {{0 0} {{map[] true}} map[unittest_plugin0:0xc000122368] 0}
    executor_test.go:216: PASS: Execute(*context.emptyCtx,*v1.ExecuteRequest,[]grpc.CallOption)
--- PASS: TestExecutorFailure (0.00s)
PASS
ok      github.com/dsrvlabs/vatz/manager/executor       (cached)
=== RUN   TestPluginHealthCheckSuccess
    healthcheck_test.go:47: PASS:       Verify(*context.emptyCtx,*emptypb.Empty,[]grpc.CallOption)
--- PASS: TestPluginHealthCheckSuccess (0.00s)
=== RUN   TestPluginHealthCheckFailed
    healthcheck_test.go:105: PASS:      Verify(*context.emptyCtx,*emptypb.Empty,[]grpc.CallOption)
    healthcheck_test.go:105: PASS:      Verify(*context.emptyCtx,*emptypb.Empty,[]grpc.CallOption)
--- PASS: TestPluginHealthCheckFailed (0.00s)
=== RUN   TestVatzHealthCheck
--- PASS: TestVatzHealthCheck (0.00s)
PASS
ok      github.com/dsrvlabs/vatz/manager/healthcheck    (cached)
=== RUN   TestDBWrite
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newWriter vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Create DB Instance"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newReader vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"AddPlugin"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Get test"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"DeletePlugin"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Get test"}
--- PASS: TestDBWrite (0.00s)
=== RUN   TestDBNotExist
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newWriter vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Create DB Instance"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newReader vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"AddPlugin"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Get not-exist"}
--- PASS: TestDBNotExist (0.00s)
=== RUN   TestDBList
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newWriter vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Create DB Instance"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newReader vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"AddPlugin"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"AddPlugin"}
{"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"List Plugin"}
--- PASS: TestDBList (0.00s)
=== RUN   TestPluginManager
{"level":"info","module":"plugin","time":"2023-01-16T10:11:01-06:00","message":"Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newWriter /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/manager/plugin/vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"Create DB Instance"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"AddPlugin"}
{"level":"info","module":"plugin","time":"2023-01-16T10:11:02-06:00","message":"Start plugin cosmos-active"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newReader /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/manager/plugin/vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"Get cosmos-active"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newReader ./vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"Get cosmos-active"}
--- PASS: TestPluginManager (0.75s)
=== RUN   TestPluginList
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newWriter ./vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"Create DB Instance"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"AddPlugin"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"AddPlugin"}
{"level":"info","module":"plugin","time":"2023-01-16T10:11:02-06:00","message":"List"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newReader /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/manager/plugin/vatz.db"}
{"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"List Plugin"}
--- PASS: TestPluginList (0.00s)
PASS
ok      github.com/dsrvlabs/vatz/manager/plugin (cached)
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
=== RUN   TestRPCs
{"level":"info","module":"rpc","time":"2023-01-16T10:09:48-06:00","message":"start rpc server"}
{"level":"info","module":"rpc","time":"2023-01-16T10:09:48-06:00","message":"start gRPC gateway server 127.0.0.1:19091"}
{"level":"info","module":"rpc","time":"2023-01-16T10:09:48-06:00","message":"start gRPC server 127.0.0.1:19090"}
--- PASS: TestRPCs (1.00s)
=== RUN   TestPluginStatus
    rpc_test.go:89: PASS:       PluginStatus(*context.emptyCtx)
--- PASS: TestPluginStatus (0.00s)
PASS
ok      github.com/dsrvlabs/vatz/rpc    (cached)
=== RUN   TestVersion
--- PASS: TestVersion (0.00s)
PASS
ok      github.com/dsrvlabs/vatz/utils  (cached)
 dongyookang DK 🐵   ~/ffplay/GolandProjects/dsrvlabs/vatz   log
 

```

**Comment by heejin-github** [comment]
> @heejin-github
> 
> I Confirmed our common logs is formatted as below
> 
> image
> 
> image
> 
> Are you trying to cover this part as well, or will be covered in another issue?
> 
> ```
>  make test    
> # github.com/dsrvlabs/vatz/manager/plugin.test
> ld: warning: -no_pie is deprecated when targeting new OS versions
> # github.com/dsrvlabs/vatz/cmd.test
> ld: warning: -no_pie is deprecated when targeting new OS versions
> ?       github.com/dsrvlabs/vatz        [no test files]
> === RUN   TestInitCmd
> {"level":"info","module":"main","time":"2023-01-16T10:10:20-06:00","message":"init"}
> {"level":"info","module":"main","time":"2023-01-16T10:10:20-06:00","message":"create file default.yaml"}
> {"level":"info","module":"main","time":"2023-01-16T10:10:20-06:00","message":"init"}
> {"level":"info","module":"main","time":"2023-01-16T10:10:20-06:00","message":"create file hello.yaml"}
> --- PASS: TestInitCmd (0.00s)
> === RUN   TestPluginInstall
> {"level":"info","module":"plugin","time":"2023-01-16T10:10:20-06:00","message":"Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status at /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/cmd"}
> {"level":"info","module":"plugin","time":"2023-01-16T10:10:20-06:00","message":"Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status"}
> {"level":"info","module":"db","time":"2023-01-16T10:10:24-06:00","message":"newWriter /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/cmd/vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:10:24-06:00","message":"Create DB Instance"}
> {"level":"info","module":"db","time":"2023-01-16T10:10:24-06:00","message":"AddPlugin"}
> --- PASS: TestPluginInstall (4.38s)
> PASS
> ok      github.com/dsrvlabs/vatz/cmd    (cached)
> testing: warning: no tests to run
> PASS
> ok      github.com/dsrvlabs/vatz/manager/api    (cached) [no tests to run]
> === RUN   TestDefaultConfig
> --- PASS: TestDefaultConfig (0.00s)
> === RUN   TestOverrideDefaultValues
> --- PASS: TestOverrideDefaultValues (0.00s)
> === RUN   TestURLConfig
> --- PASS: TestURLConfig (0.00s)
> === RUN   TestNotExistConfigFile
> {"level":"info","module":"config","time":"2023-01-16T10:09:48-06:00","message":"Load Config not_existing_file.yaml"}
> --- PASS: TestNotExistConfigFile (0.00s)
> === RUN   TestInvalidYAMLFormat
> {"level":"info","module":"config","time":"2023-01-16T10:09:48-06:00","message":"Load Config default.yaml"}
> {"level":"error","module":"config","time":"2023-01-16T10:09:48-06:00","message":"parseYAML Error: yaml: line 3: mapping values are not allowed in this context"}
> --- PASS: TestInvalidYAMLFormat (0.00s)
> === RUN   TestGetConfig
> {"level":"info","module":"config","time":"2023-01-16T10:09:48-06:00","message":"Load Config default.yaml"}
> --- PASS: TestGetConfig (0.00s)
> PASS
> ok      github.com/dsrvlabs/vatz/manager/config (cached)
> === RUN   TestMessageHandler
> --- PASS: TestMessageHandler (0.00s)
> PASS
> ok      github.com/dsrvlabs/vatz/manager/dispatcher     (cached)
> === RUN   TestExecutorSuccess
> Status {{0 0} {{map[] true}} map[unittest_plugin127.0.0.110002:0xc000122318] 0}
>     executor_test.go:104: PASS: Execute(*context.emptyCtx,*v1.ExecuteRequest,[]grpc.CallOption)
> --- PASS: TestExecutorSuccess (0.00s)
> === RUN   TestExecutorFailure
> Status {{0 0} {{map[] true}} map[unittest_plugin0:0xc000122340] 0}
>     executor_test.go:216: PASS: Execute(*context.emptyCtx,*v1.ExecuteRequest,[]grpc.CallOption)
> Status {{0 0} {{map[] true}} map[unittest_plugin0:0xc000122368] 0}
>     executor_test.go:216: PASS: Execute(*context.emptyCtx,*v1.ExecuteRequest,[]grpc.CallOption)
> --- PASS: TestExecutorFailure (0.00s)
> PASS
> ok      github.com/dsrvlabs/vatz/manager/executor       (cached)
> === RUN   TestPluginHealthCheckSuccess
>     healthcheck_test.go:47: PASS:       Verify(*context.emptyCtx,*emptypb.Empty,[]grpc.CallOption)
> --- PASS: TestPluginHealthCheckSuccess (0.00s)
> === RUN   TestPluginHealthCheckFailed
>     healthcheck_test.go:105: PASS:      Verify(*context.emptyCtx,*emptypb.Empty,[]grpc.CallOption)
>     healthcheck_test.go:105: PASS:      Verify(*context.emptyCtx,*emptypb.Empty,[]grpc.CallOption)
> --- PASS: TestPluginHealthCheckFailed (0.00s)
> === RUN   TestVatzHealthCheck
> --- PASS: TestVatzHealthCheck (0.00s)
> PASS
> ok      github.com/dsrvlabs/vatz/manager/healthcheck    (cached)
> === RUN   TestDBWrite
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newWriter vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Create DB Instance"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newReader vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"AddPlugin"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Get test"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"DeletePlugin"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Get test"}
> --- PASS: TestDBWrite (0.00s)
> === RUN   TestDBNotExist
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newWriter vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Create DB Instance"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newReader vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"AddPlugin"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Get not-exist"}
> --- PASS: TestDBNotExist (0.00s)
> === RUN   TestDBList
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newWriter vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"Create DB Instance"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"newReader vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"AddPlugin"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"AddPlugin"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:01-06:00","message":"List Plugin"}
> --- PASS: TestDBList (0.00s)
> === RUN   TestPluginManager
> {"level":"info","module":"plugin","time":"2023-01-16T10:11:01-06:00","message":"Install new plugin github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newWriter /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/manager/plugin/vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"Create DB Instance"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"AddPlugin"}
> {"level":"info","module":"plugin","time":"2023-01-16T10:11:02-06:00","message":"Start plugin cosmos-active"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newReader /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/manager/plugin/vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"Get cosmos-active"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newReader ./vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"Get cosmos-active"}
> --- PASS: TestPluginManager (0.75s)
> === RUN   TestPluginList
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newWriter ./vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"Create DB Instance"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"AddPlugin"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"AddPlugin"}
> {"level":"info","module":"plugin","time":"2023-01-16T10:11:02-06:00","message":"List"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"newReader /Users/dongyookang/ffplay/GolandProjects/dsrvlabs/vatz/manager/plugin/vatz.db"}
> {"level":"info","module":"db","time":"2023-01-16T10:11:02-06:00","message":"List Plugin"}
> --- PASS: TestPluginList (0.00s)
> PASS
> ok      github.com/dsrvlabs/vatz/manager/plugin (cached)
> ?       github.com/dsrvlabs/vatz/manager/types  [no test files]
> ?       github.com/dsrvlabs/vatz/mocks  [no test files]
> === RUN   TestRPCs
> {"level":"info","module":"rpc","time":"2023-01-16T10:09:48-06:00","message":"start rpc server"}
> {"level":"info","module":"rpc","time":"2023-01-16T10:09:48-06:00","message":"start gRPC gateway server 127.0.0.1:19091"}
> {"level":"info","module":"rpc","time":"2023-01-16T10:09:48-06:00","message":"start gRPC server 127.0.0.1:19090"}
> --- PASS: TestRPCs (1.00s)
> === RUN   TestPluginStatus
>     rpc_test.go:89: PASS:       PluginStatus(*context.emptyCtx)
> --- PASS: TestPluginStatus (0.00s)
> PASS
> ok      github.com/dsrvlabs/vatz/rpc    (cached)
> === RUN   TestVersion
> --- PASS: TestVersion (0.00s)
> PASS
> ok      github.com/dsrvlabs/vatz/utils  (cached)
>  dongyookang DK 🐵   ~/ffplay/GolandProjects/dsrvlabs/vatz   log
>  
> ```


what's the problem?

**Comment by heejin-github** [comment]
> > what's the problem?
> 
> because, I thought this issue covers Align log format overall, doesn't this issue cover `make test` command in same format too? because stdout for make command isn't formatted as above.

I understood what you point out :)
This patch set the logger output format for the fileout. so, the `make test` command should not related with this patch.

however, I think `make test` will use stdout for printing logs without any formatting. we didn't set any log format for the test.
because output format was set in init(), test command wouldn't applied log format.
https://github.com/dsrvlabs/vatz/blob/main/main.go#L12-L14

anyway, I think we'd better handle it on another issue, if we should fix it.
but, I'm not sure we have to fix it for the test case actually.

**Review by xellos00 — APPROVED** [review]

**Pull request merged**
