### PR TITLE
Add new flag `--all` on CLI command `vatz init`

### LINKED ISSUE #436: Update Config format
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---

from @xellos00 
I want to config include all options for plugins with default setting in default.yaml

from @heejin-github 
give another option to create default.yaml
- w/o plugin info in default.yaml / no options 
- w plugin info in default.yaml / with option

Create two version of config yaml file by its command on `vatz init`

### PR DESCRIPTION
**Pull request by xellos00**
…ing in config yaml file.

### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)
close #436 

**Summary**
develop vatz init that provide official plugins default port numbers and name. 

---

```
 dongyookang DK 💡   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-436-RE ±
 make coverage                                                                                                                           
fatal: No names found, cannot describe anything.
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    2.357s  coverage: 22.1% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.501s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.768s  coverage: 79.4% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.633s  coverage: 7.8% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       1.044s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.900s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 6.744s  coverage: 50.6% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  1.181s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    2.490s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.202s  coverage: 7.1% of statements
 dongyookang DK 💡   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-436-RE ±
```

### CODE REVIEW

**Comment by xellos00** [comment]
@heejin-github 
I will update port numbers when you finish issue 
- https://github.com/dsrvlabs/vatz/issues/456

Please, let me know when you finish issue above.

**Review by heejin-github — APPROVED** [review]
LGTM

**Comment by rootwarp** [comment]
```
ok      github.com/dsrvlabs/vatz/utils  0.006s
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    1.650s  coverage: 22.1% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.009s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.011s  coverage: 79.4% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.011s  coverage: 7.8% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       0.016s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.012s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 1.208s  coverage: 50.6% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  0.011s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    1.014s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.007s  coverage: 7.1% of statements
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=ISSUE-436-RE' -X 'github.com/dsrvlabs/vatz/utils.Commit=92c7ea9'" -v
github.com/dsrvlabs/vatz
```

**Comment by rootwarp** [comment]
@xellos00 
Could you please my comment from #458?
There is a bug to create template file and we need recover some codes.

**Comment by xellos00** [comment]
> @xellos00 Could you please my comment from #458? There is a bug to create template file and we need recover some codes.

I will raise a new PR that would recover issue #458.

**Comment by xellos00** [comment]
> > @xellos00 Could you please my comment from #458? There is a bug to create template file and we need recover some codes.
> 
> I will raise a new PR that would recover issue #458.

@rootwarp 
This PR include --home on init.go

**Comment by rootwarp** [comment]
```
rootwarp@mindhack ~/g/d/vatz ISSUE-436-RE > make coverage
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    1.576s  coverage: 23.5% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.008s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.011s  coverage: 79.4% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.011s  coverage: 7.8% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       0.014s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.011s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 1.417s  coverage: 50.6% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  0.009s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    1.014s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.007s  coverage: 7.1% of statements
```

**Review by rootwarp — APPROVED** [review]
LGTM

**Pull request merged**
