### PR TITLE
Divide Logs by its level Debug, Info, trace. 

### PR DESCRIPTION
**Pull request by xellos00**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

close: #485 

**Summary**

As explained,  on #485
-  [Case 1](https://github.com/dsrvlabs/vatz/issues/485#issuecomment-1661065595), `Info` level logs are recorded on the logs as default unless user enable debug mode with flag `debug` which's showing all traceable `debug` logs. 
- [Case 2](https://github.com/dsrvlabs/vatz/issues/485#issuecomment-1661065785),  running Vatz doesn't clear show its even drives per its log level including `Info` `debug`, and `trace` 
---

```
 dongyookang DK 🐵   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-485
 make coverage
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    2.779s  coverage: 23.6% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.517s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.644s  coverage: 77.8% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     1.386s  coverage: 7.1% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       1.253s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.401s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 7.409s  coverage: 51.0% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  1.541s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    1.791s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.973s  coverage: 4.9% of statements
 dongyookang DK 🐵   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-485

```

### CODE REVIEW

**Comment by xellos00** [comment]
# Init `VATZ`

## Default 
 ./vatz init
2023-08-04T18:42:04-05:00 INF Initialize DB /Users/dongyookang/.vatz/vatz.db module=db


## debug
```
 ./vatz --debug init                                 
2023-08-04T18:42:13-05:00 DBG init module=main
2023-08-04T18:42:13-05:00 DBG home path ~/.vatz module=main
2023-08-04T18:42:13-05:00 DBG create file default.yaml module=main
2023-08-04T18:42:13-05:00 DBG Load Config default.yaml module=config
2023-08-04T18:42:13-05:00 DBG Plugin dir /Users/dongyookang/.vatz module=main
2023-08-04T18:42:13-05:00 DBG Create DB Instance module=db
2023-08-04T18:42:13-05:00 INF Initialize DB /Users/dongyookang/.vatz/vatz.db module=db
2023-08-04T18:42:13-05:00 DBG Remove old DB file module=db
2023-08-04T18:42:13-05:00 DBG Create new DB file module=db
2023-08-04T18:42:13-05:00 DBG Create DB Instance module=db
 dongyookang DK 🔥   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-485 ±
```

**Comment by rootwarp** [comment]
```
ok      github.com/dsrvlabs/vatz/utils  0.008s
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    1.903s  coverage: 23.6% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.013s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.011s  coverage: 77.8% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.019s  coverage: 7.1% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       0.015s  coverage: 67.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.015s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 1.386s  coverage: 51.0% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  0.015s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    1.018s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  0.009s  coverage: 4.9% of statements
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=ISSUE-485' -X 'github.com/dsrvlabs/vatz/utils.Commit=ad45708'" -v
github.com/dsrvlabs/vatz
```

**Review by rootwarp — APPROVED** [review]
Seems simple changing log level.

LGTM

**Review by heejin-github — APPROVED** [review]
LGTM

**Review by meetrick — APPROVED** [review]
LGTM

**Pull request merged**
