### PR TITLE
Separate Monitoring in folder structures

### LINKED ISSUE #390: Separate Monitoring module into another folder structures
- Parents: #392 

---

## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---

### PR DESCRIPTION
**Pull request by xellos00**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)
Close #390 

**Summary**
Separate Monitoring in folder structures and add some test cases. 

---

image

### CODE REVIEW

**Comment by xellos00** [comment]
image

**Comment by xellos00** [comment]
@dsrvlabs/validator 
somewhat close test will be requires. Please, review with your test to check prometheus is working properly.

**Review by rootwarp — APPROVED** [review]
LGTM

**Review by heejin-github — APPROVED** [review]
LGTM.
monitoring works well.

**Pull request merged**
