### PR TITLE
Update Codes to pass Golint

### LINKED ISSUE #344: Update Codes to pass Golint
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---

### PR DESCRIPTION
**Pull request by kim201212**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [x] Enhancement
- [ ] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

**Related:** # (issue)
close #344 

**Summary**
Update Codes to pass Golint

---

```shell
hg  ~/workspace/vatz   lint  golangci-lint run -v              
INFO [config_reader] Config search paths: [./ /Users/hg/workspace/vatz /Users/hg/workspace /Users/hg /Users /] 
INFO [lintersdb] Active 9 linters: [deadcode errcheck gosimple govet ineffassign staticcheck typecheck unused varcheck] 
INFO [loader] Go packages loading at mode 575 (exports_file|imports|name|types_sizes|compiled_files|deps|files) took 449.86046ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 5.367997ms 
INFO [linters context/goanalysis] analyzers took 0s with no stages 
INFO [runner] Issues before processing: 21, after processing: 0 
INFO [runner] Processors filtering stat (out/in): autogenerated_exclude: 21/21, exclude: 21/21, exclude-rules: 0/21, path_prettifier: 21/21, identifier_marker: 21/21, cgo: 21/21, filename_unadjuster: 21/21, skip_files: 21/21, skip_dirs: 21/21 
INFO [runner] processing took 679.588µs with stages: identifier_marker: 235.984µs, autogenerated_exclude: 195.417µs, path_prettifier: 153.163µs, skip_dirs: 43.424µs, exclude-rules: 38.736µs, cgo: 4.431µs, filename_unadjuster: 2.994µs, nolint: 2.563µs, max_same_issues: 667ns, max_from_linter: 298ns, uniq_by_line: 285ns, skip_files: 253ns, source_code: 218ns, severity-rules: 196ns, diff: 190ns, exclude: 184ns, max_per_file_from_linter: 183ns, path_shortener: 162ns, sort_results: 134ns, path_prefixer: 106ns 
INFO [runner] linters took 126.621748ms with stages: goanalysis_metalinter: 125.877424ms 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 7 samples, avg is 58.1MB, max is 61.5MB 
INFO Execution took 599.658798ms  
```

### CODE REVIEW

**Comment by kim201212** [comment]
Successful Golang Linter (`golangci-lint`) in Actions

image

**Review by meetrick — APPROVED** [review]
LGTM

**Review by heejin-github — APPROVED** [review]
LGTM

**Review by gnongs — APPROVED** [review]
LGTM!

**Comment by rootwarp** [comment]
```
rootwarp@mindhack ~/g/d/vatz lint? > make coverage
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    7.382s  coverage: 24.1% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.009s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.010s  coverage: 77.8% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.013s  coverage: 7.1% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       0.013s  coverage: 66.7% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.011s  coverage: 40.8% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 6.183s  coverage: 51.0% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  0.011s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    1.014s  coverage: 65.0% of statements
ok      github.com/dsrvlabs/vatz/utils  0.008s  coverage: 3.6% of statements
rootwarp@mindhack ~/g/d/vatz lint? >
```

**Review by rootwarp — COMMENTED** [review]
@kim201212 @xellos00 
what do you think add "lint check" command on `Makefile`?
If so, it will be useful to contributors before issue PR.

**Comment by kim201212** [comment]
> @kim201212 @xellos00 what do you think add "lint check" command on `Makefile`? If so, it will be useful to contributors before issue PR.

That's a good idea.
I added the commit for adding "lint" in the Makefile.
https://github.com/dsrvlabs/vatz/pull/516/commits/c8bfe7f83dd04e820227bf1ada708e9a3eb47d2f

**Pull request merged**
